### ISSUE TITLE
Missing instruction to have multiple camera views like in the README.md screenshot

### ISSUE THREAD

**Issue by orangpelupa** [kinsi55/CS_BeatSaber_Camera2#10]
i;ve looked at the wiki pages, but its Missing instruction to have multiple camera views like in the README.md screenshot

**Comment by kinsi55** [comment]
https://github.com/kinsi55/CS_BeatSaber_Camera2/wiki

> Repositioning the Camera windows can be done via drag and drop, resizing them can be done like one would expect with the bottom right corner on the preview.
> Positioning postionable cameras (Third person) can be done from within VR by holding the respective camera with your trigger and moving it around.

Granted, newly created cameras being fullscreen is not very clear, I've already changed it so that newly added cameras become a smaller window instead of taking up the entire screen by default, this will be part of the next update.

![grafik](https://user-images.githubusercontent.com/8348306/111018921-49ca0a00-83bc-11eb-9796-f35fdf44a0df.png)

**Comment by orangpelupa** [comment]
sorry, do you have a video how to do it? I;ve traced the in-VR laser to the 8 edges of the preview window and cant resize it

**Comment by kinsi55** [comment]
Well yeah thats the only thing that I have not yet figured out if / how I could move it to VR. I dont think theres really any good way to do it.

**Comment by orangpelupa** [comment]
yeah i imagine on VR you would need to add a "desktop view" window in a "desktop layout" submenu or something. much easier using the desktop view.

btw can the view be adjustable by its 4 sides instead of just from the bottom right?

**Comment by kinsi55** [comment]
Technically yes, practically I need to manually implement them all. I'll think about it.

**Comment by finnock** [comment]
this doesnt work for me at all. I have 3 cameras set up. The "Main" First person camera and two positioned cameras.
Now in the desktop view of the game i cannot drag and drop anything, i can only see the last camera. Left click doesnt do anything and right click shows me: 

```
  ---------------------------
  FYI
  ---------------------------
  There is no desktop settings for Camera2, everything is done ingame!
  ---------------------------
  OK   
  ---------------------------
```

is there anything additional to configure?? Also: is there any possibility for the viewers (on couch, i dont stream) to manually switch between camera views? like hit button 1 for cam 1 and button 2 for cam 2? that would be incredibly awesome.

Cheers
Jan

**Comment by kinsi55** [comment]
Yes, all of that is possible and all of it is outlined in the Wiki.

**Comment by HananoshikaYomaru** [comment]
When I set up two cameras, the first person camera is not visible on the screen. Do I need to make it visible and then drag and drop on the desktop? @kinsi55

**Comment by kinsi55** [comment]
When you add a new camera it is full screen by default, so you need to resize and position it as you like. This is of the things that changes in the next update.

**Comment by kinsi55** [comment]
Massively improved in the current 0.3.8 Beta release: https://github.com/kinsi55/CS_BeatSaber_Camera2/releases/tag/v0.3.8
