### ISSUE TITLE
Input Delay in FPFC (AMD issue maybe?) & Scene Toggles Broken in FPFC

### ISSUE THREAD

**Issue by Xentha** [kinsi55/CS_BeatSaber_Camera2#109]
So as a baseline, there is input lag in FPFC, where it takes a fraction of a second for anything to occur, whether it be turning camera, clicking things, or the audio sync in general. This surfaced when I swapped to an AMD based GPU, so may be related. Going from 1.27 to 1.29.1 tightened this up a bit but it's still present.

Removing Camera2 removes the input delay, so it is most certainly how the mod is functioning.

Part of this however, seems tied to cameras being visible when they're not supposed to be while in FPFC. Even with a camera fully disabled on all scenes, it seems to still remain visible no matter what.

**Comment by kinsi55** [comment]
It is in fact an AMD issue. Disable Vsync for BS in its driver

**Comment by Xentha** [comment]
Yep that did it! Specifically I had to turn it from 'Off, unless application specifies' to 'Always off'. Glad it was that simple. Thank you! It is still odd that cameras remain visible during FPFC even if toggled off, but the main issue is solved.

**Comment by kinsi55** [comment]
> Even with a camera fully disabled on all scenes, it seems to still remain visible no matter what.

Please make sure you fully understand how the Scenes System works, check the Wiki on that

**Comment by Xentha** [comment]
Oh lordy. There's an entire flow control system to it I see.. Seems odd to me that it, under certain conditions, just disregards what you have set. I turned FPFC off on all cameras with the intent to just not have the default game camera, but according to this it then instead falls back to the camera being used for the main 'Menu' view. That's a little unintuitive honestly. But I'm sure you have your reasons, so I won't fuss about it - especially with the main issue solved.

I'll go ahead and close this now with that in mind, so, thank you again! ^^
