### ISSUE TITLE
Ability to toggle between "1st person" and "positionable" from keyboard while someone is playing.

### ISSUE THREAD

**Issue by rossc719g** [kinsi55/CS_BeatSaber_Camera2#11]
One of the features from CameraPlus that I used often was the ability to switch from 1st person to 3rd person and back by pressing f1.

It allows you to see what the player is seeing (up close) in the menus, settings, and song selection screens, and then toggle back to the 3rd person camera when playing.

Would it be possible to add some control for this for the main camera?

**Comment by Zartan57** [comment]
You can already do this with the scene feature

All details of how scenes works is in the wiki https://github.com/kinsi55/CS_BeatSaber_Camera2/wiki/Scenes

You'll just need to create your desired camera and assign to one of the custom scene.
and you'll be able to switch in middle game without pause or restart with F2-F3-F4 (respectively Custom1-Custom2-Custom3)

Actually, F1 is used to stop using custom scenes and using the apropriate scene needed.

**Comment by kinsi55** [comment]
To add to what Zartan said, if you want a gp cam in the menu and a tp cam ingame you can just assign a FP cam to the menu scene and a tp cam to the playing scene. Then you don't need to manually switch them.
