### ISSUE TITLE
Sabers not showing up on third person cameras 1.34.2

### ISSUE THREAD

**Issue by Alyng0** [kinsi55/CS_BeatSaber_Camera2#113]
I really don't know if it has to do something with the CustomSaberLite mod but, my third person cameres like the Cut camera and side view camera don't show the saber, only the trail.
IDK if it has to do something with my camera config just being copy and pasted or whatever but they don't show up.

[Camera2.zip](https://github.com/kinsi55/CS_BeatSaber_Camera2/files/14892412/Camera2.zip)

**Comment by kinsi55** [comment]
I'm just gonna straight up have to assume its an issue with CSL - They probably put the Sabers on a Visibility Layer that is by default only rendered on Firstperson Cameras, instead of putting it on the correct layer (Saber)
