### ISSUE TITLE
Mod breaking some replays

### ISSUE THREAD

**Issue by DomeVR** [kinsi55/CS_BeatSaber_Camera2#13]
So basicly:
On some maps, it seems like the replay gets comepletly broken, just the "camera" stuck to the ground, but i'm not completly sure if it's an Camera2 Bug, or more a Scoresaber Bug for replays. I also tried it with FPFC (Headset plugged in, and out individually) and without FPFC.

I can provide if needed a video of the issue.

(Uploading the config file, in case i did something funny)
[Camera2.zip](https://github.com/kinsi55/CS_BeatSaber_Camera2/files/6176764/Camera2.zip)

**Comment by kinsi55** [comment]
Have you confirmed that the replays in question work fine without Cam2?

**Comment by DomeVR** [comment]
They're fine when i replayed the map without cam2 installed.

**Comment by kinsi55** [comment]
Do the sabers still playback the movement when the bug occurs? If not, can you attach the latest.txt log file after the bug has happened?

**Comment by DomeVR** [comment]
Nope, nothing at all.

[_latest.log](https://github.com/kinsi55/CS_BeatSaber_Camera2/files/6177515/_latest.log)

**Comment by kinsi55** [comment]
I rather meant the entire game log, not just the cam2 one

**Comment by DomeVR** [comment]
[_latest.log](https://github.com/kinsi55/CS_BeatSaber_Camera2/files/6200327/_latest.log)
Whoops, totally forgot about it, there we go.

**Comment by kinsi55** [comment]
Could you (re)start the game, (try to) play a replay that is broken, and then (before) exiting the song upload that log file?

**Comment by DomeVR** [comment]
[_latest.log](https://github.com/kinsi55/CS_BeatSaber_Camera2/files/6200415/_latest.log)
There we go, basicly whilst running the song.

**Comment by kinsi55** [comment]
Ok, a couple of things:

Why do you have bs plus as well as enhancedstreamchat (Which doesnt even work on 1.14?) and SRM? Why do you have NoBuzz (Buzz isnt a thing any more on 1.14)

I would advise you to completely remove all your plugins and try to setup your BS with just mods from modassistant to test this. I see many error messages in your log from various mods.

**Comment by kinsi55** [comment]
Any Update on this?
