### ISSUE TITLE
Cameras not changing for scenes they're enabled in

### ISSUE THREAD

**Issue by aplomBomb** [kinsi55/CS_BeatSaber_Camera2#14]
At the moment I have two different cameras, a `menu cam` which is enabled in `menu` and `multiplayerMenu` scenes.
I have a second camera `play cam` which is enabled in all other scenes except for the menu scenes.

The issue is that `menu cam` is being used in every scene, it doesn't switch when entering a new scene. Is this how it's supposed to behave?

**Comment by kinsi55** [comment]
Can you Zip and attach your Camera2 config folder?

**Comment by aplomBomb** [comment]
[Camera2.zip](https://github.com/kinsi55/CS_BeatSaber_Camera2/files/6192753/Camera2.zip)

**Comment by aplomBomb** [comment]
I experienced this behavior in `0.3.6` and `0.3.10` fwiw

**Comment by kinsi55** [comment]
I am unable to replicate this. Once I go into a song the menu cam is gone for me, leaving me with just the smaller play cam. Do you think you could create a video showcasing this?

**Comment by aplomBomb** [comment]
actually no problem, i have a video already! and will do

**Comment by aplomBomb** [comment]
This is with the config i sent to you, pardon my frustrated yell haha

https://user-images.githubusercontent.com/39172279/112220599-d49cd700-8bfc-11eb-98c8-e11d149d8fb1.mp4

**Comment by aplomBomb** [comment]
[2021.03.23.16.53.29.log](https://github.com/kinsi55/CS_BeatSaber_Camera2/files/6192826/2021.03.23.16.53.29.log)

**Comment by kinsi55** [comment]
Ah yes theres your issue

```
[CRITICAL @ 17:01:37 | UnityEngine] MissingMethodException: EnvironmentEffectsFilterPreset PlayerSpecificSettings.get_environmentEffectsFilterPreset()
[CRITICAL @ 17:01:37 | UnityEngine] System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine] (TStateMachine& stateMachine) (at <9577ac7a62ef43179789031239ba8798>:0)
[CRITICAL @ 17:01:37 | UnityEngine] BeatSaberHTTPStatus.Plugin.HandleSongStart () (at <f1f629093a754a878837db29c15f6c7f>:0)
[CRITICAL @ 17:01:37 | UnityEngine] BeatSaberHTTPStatus.Plugin.OnActiveSceneChanged (UnityEngine.SceneManagement.Scene oldScene, UnityEngine.SceneManagement.Scene newScene) (at <f1f629093a754a878837db29c15f6c7f>:0)
[CRITICAL @ 17:01:37 | UnityEngine] UnityEngine.SceneManagement.SceneManager.Internal_ActiveSceneChanged (UnityEngine.SceneManagement.Scene previousActiveScene, UnityEngine.SceneManagement.Scene newActiveScene) (at <12e76cd50cc64cf19e759e981cb725af>:0)
[CRITICAL @ 17:01:37 | UnityEngine] UnityEngine.SceneManagement.SceneManager:SetActiveScene(Scene)
[CRITICAL @ 17:01:37 | UnityEngine] <ScenesTransitionCoroutine>d__36:MoveNext()
[CRITICAL @ 17:01:37 | UnityEngine] UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```

Uninstall / Update your HTTPStatus, its causing an error that prevents Cam2 from receiving the ccene switch event.

**Comment by aplomBomb** [comment]
OK!!! Thank you!

**Comment by kinsi55** [comment]
Also a little FYI: With how scenes work, you only need to enable your menu cam for "Menu", and your play fp cam for "Playing", Playing360 will look at Playing when it is empty, MultiplayerMenu will look at Menu, etc.

**Comment by aplomBomb** [comment]
Thank you, yeah I enabled it for all the unnecessary for testing purposes as I was trying to debug, thanks so much for your help!!!
