### ISSUE TITLE
Camera2 doesn't work on 1.14.0 fresh install

### ISSUE THREAD

**Issue by Excalidoom** [kinsi55/CS_BeatSaber_Camera2#15]
The plugin boots in game, I can go to the menu and start messing with the settings, but none of them do something. 1st pers, positionable, scenes ON, fov max, no changes in game, in menu, nowhere. 

Smoothing is disabled (the game one), there are no other plugins except songcore. Tried multiple times, 0 success.

Dropped the beatsaber logs and Camera2 logs. Camera2 is useless and the Unity one doesn't point to an exact error or I'm missing something

**Comment by kinsi55** [comment]
You've not attached any file, please provide your game's latest.log file and your zipped camera2 config folder

**Comment by Excalidoom** [comment]
[camera2.log.gz](https://github.com/kinsi55/CS_BeatSaber_Camera2/files/6208587/camera2.log.gz)
[Beatsaber.log.gz](https://github.com/kinsi55/CS_BeatSaber_Camera2/files/6208588/Beatsaber.log.gz)

I hate github sometimes..

**Comment by kinsi55** [comment]
What about the Cam2 config folder?

Also, you're on the ModAssistant release of Cam2, please try the latest GH release.

**Comment by Excalidoom** [comment]
I will try that again when i get home. I've tried using the github release for one of the clean boots, with manual install of ipa and all that stuff with nothing working out so i didn't try again after.

**Comment by kinsi55** [comment]
As I saw on your reddit post that you somehow assumed this would allow you to change the headset fov (which would literally make you dizzy withing minutes due to how optics work) I guess I can close this.

**Comment by Excalidoom** [comment]
Yep. Sorry for that, I am fairly new to the whole VR thing and yeah, I didn't realise how stuff works.
