### ISSUE TITLE
Camera position resets to 0,0,0 after map

### ISSUE THREAD

**Issue by Caruha** [kinsi55/CS_BeatSaber_Camera2#16]
If u have movement script, after map ends camera position resets to 0,0,0. Works fine on 0.3.6 (what is in ModAssistant).
[Camera2.zip](https://github.com/kinsi55/CS_BeatSaber_Camera2/files/6237414/Camera2.zip)
[_latest.log](https://github.com/kinsi55/CS_BeatSaber_Camera2/files/6237443/_latest.log)

https://streamable.com/hc61yb

**Comment by kinsi55** [comment]
Fixed in [0.3.25](https://github.com/kinsi55/CS_BeatSaber_Camera2/releases/tag/v0.3.25)
