### ISSUE TITLE
Make sabers more visible during gameplay

### ISSUE THREAD

**Issue by mariobrostech** [kinsi55/CS_BeatSaber_Camera2#18]
Hello,

I, like many people, have recently made the jump from Camera Plus to Camera2. I'm really enjoying it so far due to its great performance and ability to change common settings in-game. However, there is one thing that's really bugging me about Camera2, and that is the fact that sabers are much harder to see in gameplay when compared to Camera Plus. I'm not sure why this is (maybe it's the FOV?), but when comparing stock Camera Plus with stock Camera2, you can't see nearly as much of the bottom of the saber especially when using Camera2. Is there any settings you'd recommend I tweak, and, if so, is there any way you can make this the new stock setting so those who are transitioning over from Camera Plus have an easier time?

Thank you in advance!

**Comment by kinsi55** [comment]
I dont see how this would be possible - Both dont have a Z-offset by default (You could set a Z-Offset of -0.3 to -0.5 which is what a lot of people do) and Camera2 even has a higher FOV by default which should cause more stuff to be visible rather than less. You're also the first one to bring this up which makes me extra confused.

Do you think you could maybe show me some screenshots showcasing your issue?

**Comment by mariobrostech** [comment]
I don't have any screenshots, but I have 2 videos on my YouTube channel showing this behavior. Notice that in the Camera2 recording, the sabers feel much closer than in the Camera Plus recording, leading the especially the bottom of the sabers being cut off. When the action picks up, sometimes you can only see the saber trails in the Camera2 recording.

[Camera Plus recording](https://www.youtube.com/watch?v=rY4j3gJ5vgo)
[Camera2 recording](https://www.youtube.com/watch?v=Fr2i9LP2jpY)

Thanks again for your help!

**Comment by kinsi55** [comment]
I would suggest you to place your headset and one controller in a stationary position and use the other controller to go into a song, you can easily compare cam2 / cam+ this way. Camera2 and CameraPlus for that matter are really just fancy configuration interfaces of Unity's built in cameras which handle the entire rending - If you use the same settings in both it should pretty much look the same, and I dont really see an obvious difference in both of your linked recordings to be honest.

**Comment by mariobrostech** [comment]
Ok, I'll play around with the Z-offset values and FOV like you suggested in your original comment, and I'll get back to you with my results. I recently had to RMA one of my controllers, so it might be a little while before I can get around to testing this again.

Thanks again for your help!

**Comment by kinsi55** [comment]
Closing as I guess its not an issue any more.
