### ISSUE TITLE
Cant change Camera2 Settings

### ISSUE THREAD

**Issue by roboltz** [kinsi55/CS_BeatSaber_Camera2#19]
When I right click the screen with camera 2 it says the settings are in game but I can't find them. Is it possibly a bug or is it somewhere else?

**Comment by kinsi55** [comment]
There is a Camera2 button in the "mods" section in the main menu

**Comment by roboltz** [comment]
I definitely don't see it. I think it's a bug. here is a video. [https://streamable.com/ytuoew](url). The mod definitely is downloaded because the fov is higher and it's smoother so idk what's happening.

**Comment by roboltz** [comment]
Is there a dependency required for it to show?

**Comment by kinsi55** [comment]
Can you attach your latest log file from the game's logs folder

**Comment by roboltz** [comment]
[INFO @ 14:05:03 | Camera2] Camera2 initialized.
[DEBUG @ 14:05:04 | Camera2] OnApplicationStart
[NOTICE @ 14:05:07 | Camera2] Game is ready, Initializing...
[DEBUG @ 14:09:14 | Camera2] OnApplicationQuit

**Comment by roboltz** [comment]
from Beat Saber > Logs > Camera2 > _latest.log

**Comment by kinsi55** [comment]
Thats the camera2 specific log, I need to game one (Directly in the logs folder)

**Comment by roboltz** [comment]
I downloaded the latest version and nothing changed

**Comment by roboltz** [comment]
[_latest.log](https://github.com/kinsi55/CS_BeatSaber_Camera2/files/6259861/_latest.log)

**Comment by roboltz** [comment]
that is the game log

**Comment by kinsi55** [comment]
You seem to have somehow corrupted your Scenes.json config in the Camera2 folder - Delete that and it should work. I'll add better handling incase this happens.

**Comment by roboltz** [comment]
thank you i will try that now.

**Comment by roboltz** [comment]
It works now. I do remember trying to edit the file to change the settings because it didn't show up before so that's my fault.
