### ISSUE TITLE
Positionable camera settings not saving from inside a map

### ISSUE THREAD

**Issue by OoDeeR** [kinsi55/CS_BeatSaber_Camera2#21]
If you enter a map, pause and change the camera position/angle, those changes will only persist for as long as you're in that map. They'll revert when going back to the menu and entering other maps/replays.
Edit: this was in v0.3.6. Disregard if it's already fixed in the current version.

**Comment by kinsi55** [comment]
This should be fixed in latest, please confirm and close the issue if that's the case.

**Comment by kinsi55** [comment]
Closed as I guess its not an issue any more.
