### ISSUE TITLE
Parameter to specify an exact time for keyframe

### ISSUE THREAD

**Issue by pmcthor777** [kinsi55/CS_BeatSaber_Camera2#24]
Is it possible to have a parameter in the movement script to specify an exact time to start a keyframe?

**Comment by kinsi55** [comment]
No, Movement Scripts are linear - Whenever one ends the next one starts, so if you do the math you can accomplish what you're looking for, but setting a specific start time of a keyframe is not possible as this would pose a completely new set of issues like overlapping keyframes etc.

**Comment by pmcthor777** [comment]
OK, thanks for the reply.
