### ISSUE TITLE
unlinked dynamic/static lights

### ISSUE THREAD

**Issue by fuyushi** [kinsi55/CS_BeatSaber_Camera2#25]
I would like a function to only have dynamic lights enabled on the desktop view, whilst playing on static lights. I guess the same could be useful for cut particles and debris

**Comment by kinsi55** [comment]
The lights thing isn't possible unfortunately. As for debris, you can already do that, the basegame reduce debris option will disable debris in VR, but it stays active for the desktop assuming you have debris on. Lastly as far as the cut particles go, offering an option to hide them only in VR is beyond the things that camera2 should do - camera2 will never get any options to modify the VR view in any way.
