### ISSUE TITLE
Camera moves to a position beside me when I start playing.

### ISSUE THREAD

**Issue by Sivanot** [kinsi55/CS_BeatSaber_Camera2#27]
I've made a camera, positioned it behind me, and set it to be active in all scenes. But when I start playing a song, it moves to a position beside me, forcing me to pause and move it manually. It always resets to this same position when I start a map, and moving it in the map doesn't effect the position I wanted when I go back to the menu.  
I'm using the latest version of the mod, and I'm playing BS on steam with the Quest 2 through Oculus Link if it's important.

Am I doing something wrong or is this a bug?

**Comment by kinsi55** [comment]
Are you *sure* you are on the latest version? Because if you have a room adjust set, that used to cause that and has been fixed for a while

**Comment by Sivanot** [comment]
I installed the mod through ModAssistant, and it has the same version number there as the latest release.

**Comment by kinsi55** [comment]
Can you Screenshot me what the left settings panel looks like ingame?

**Comment by Sivanot** [comment]
So i tested it again when i went to get the screenshot, and suddenly it seems to be working fine. Maybe I wasn't actually playing on the right version before somehow? I also removed any room rotation since steamvr had me facing the right way for once.  So it seems to be fixed now, thanks for trying to help anyway though.

**Comment by kinsi55** [comment]
👍
