### ISSUE TITLE
Steamlink support

### ISSUE THREAD

**Issue by DaVarga** [kinsi55/CS_BeatSaber_Camera2#32]
Hello
On my setup, the viewers watch via Steamlink on my Android Smart TV. However, the mod only affects the window on the PC screen. The image that is transmitted via Steamlink to my TV does not seem to be affected by the mod at all.
Is there possibly any settings that I need to set on the PC in Steam or on the Steamlink client?

**Comment by kinsi55** [comment]
Uhm, to be fair I dont exactly know how this works. I think what Steam VR would do in this case is transmit your VR View (Which you can also view from the SteamVR context menu). You would need some way to transmit the Beat Saber window, I'm pretty sure they must have some option to do that but I cant exactly help you find it. Regardless this is beyond the responsibility of Camera2
