### ISSUE TITLE
lockable camera screen position

### ISSUE THREAD

**Issue by LicensedCrime** [kinsi55/CS_BeatSaber_Camera2#33]
The screen position of secondary cameras should be locked while not in config menu, or there should be a lock screen position toggle button.
It happens very often, that you accidentally move the screen while in FPFC mode and there is no way to move it back without using the VR mode of the game.

**Comment by kinsi55** [comment]
I don't understand this part 

>and there is no way to move it back without using the VR mode of the game.

You move the views on the desktop, you don't need the VR view for that.

That being said I could improve this a bit, for the while, when focusing the game use rightclick instead of left click, this way you won't accidently move any cameras.

**Comment by LicensedCrime** [comment]
> You move the views on the desktop, you don't need the VR view for that.
If you start the game in FPFC mode, and you try to move the screen, the mouse locks to the in game cursor.
And this is why you cant move it on the desktop.

**Comment by kinsi55** [comment]
Ah, look into fpfctoggle in SiraUtil, much more convenient than starting in normal fpfc

**Comment by LicensedCrime** [comment]
Much thx

**Comment by kinsi55** [comment]
While not exactly what you've asked for, this will resolve the underlying issue. I will however keep this open as I think adding such a setting makes sense https://github.com/kinsi55/CS_BeatSaber_Camera2/commit/0a9b007c891dc0a5008e1e956a27ad0ce3d1f04d

Not sure when I'll publish the update containing this (and possibly the pos lock)

**Comment by kinsi55** [comment]
Implemented in latest release
