### ISSUE TITLE
Update the view in game when a camera configuration file has been updated

### ISSUE THREAD

**Issue by bleuthoot-sven** [kinsi55/CS_BeatSaber_Camera2#35]
Not everything in that's in the camera configuration file can be easily or precisely changed, for that I normally change the JSON file in the `UserData` folder.

Currently, when I update a configuration file in the `UserData`, I have to restart the game in order for it to update. I would like that the view updates when I update one of the camera's configuration files so I can see the changes that I made instantly.

This would make it easier to view changes to a Positionable camera.

**Comment by kinsi55** [comment]
As outlined in the Wiki, you can reload the Camera2 configuration while the game is running by pressing CTRL+Shift+F1

**Comment by bleuthoot-sven** [comment]
Didn't read the wiki, sorry for that. This option will help.

Thanks.

**Comment by chrisliebaer** [comment]
I would like to point out that this does not reload **active** movement scripts. This means that old movement scripts will continue to run (and loop). While this might not matter in case of song synced scripts. If you happen to have a movement script that is also running in the menus, pressing Ctrl + Shift + F1 will not affect those. As a workaround I had to re-eneable the script to be active in menus as well.

I understand that there are difficulties with movement scripts that are synced to specific songs, but I also believe that there is very little reason to keep outdated scripts running. In the end, this appears to be more of a debug tool, so weird behaviour should be acceptable.

At least this is true for the v0.5.3 release.
