### ISSUE TITLE
Better handling of invalid camera JSON

### ISSUE THREAD

**Issue by Protected** [kinsi55/CS_BeatSaber_Camera2#42]
When a camera config file contains invalid JSON (for example due to a typo), camera2 will render a "positionable" camera panel at origin, except it's flat dark grey and can't actually be moved. This panel shows in every scene and is irremovable, even if you remove the broken config file and press ctrl+shift+f1. You need to restart the game to get rid of it.

This was a bit of a chore to diagnose, especially since the typo was very hard to see (; instead of :). It would be nicer if invalid cameras were ignored, possibly with an alert message. They should also reload properly.

**Comment by kinsi55** [comment]
If a cam fails to load for whatever reason it will already [log the error to the Log file](https://github.com/kinsi55/CS_BeatSaber_Camera2/blob/90f20dfb48f95c4119a2323fe7e7adcf9ab08bc0/Managers/CamManager.cs#L49-L59), however I have not thought of removing the in-broken-state camera. I'll change this behaviour.
