### ISSUE TITLE
Add Grabbers for placing cameras / Rotation Reset / "farZ"

### ISSUE THREAD

**Issue by Kilghardt** [kinsi55/CS_BeatSaber_Camera2#44]
Placing that camera was quite a pain in fpfc
Grabbers, such as those in Blender for example, would really help with placing straight facing cameras.
Also being able to reset the cameras rotation would help with straightening. Not even sure whether mine is straight because the config says "0" in the only rotations fields i can find.

![image](https://user-images.githubusercontent.com/85838494/131872147-e0577794-e215-42fe-98bc-de3910afa021.png)
![image](https://user-images.githubusercontent.com/85838494/131872289-8fc16d93-4e98-4790-9548-22690540d5d9.png)

**Comment by Kilghardt** [comment]
Actually additionally renaming the "farZ" option in the config would help eliminate any confusion as for what this option does.

**Comment by kinsi55** [comment]
I guess you have not seen the new update yet - Cameras now snap to 45 degree angles when moved around. For anything beyond / more exact adjustment you're meant to edit the config manually.

**Comment by Kilghardt** [comment]
Oh i didn't realise that. Guess that fixes my issue then.
