### ISSUE TITLE
Feature: Reload movement JSON on EOF.

### ISSUE THREAD

**Issue by TheBitcoinBaron** [kinsi55/CS_BeatSaber_Camera2#50]
Not sure whether this should be a new variable or just hard coded in...

At the moment, It's pretty tough to plan out a sequence of movement keyframes. One has to basically put in new keyframes, with numbers, save and then reload the game for movement script to be reloaded. Or put on the VR headset, switch to a different camera, and then switch back, both of which require time and effort.

A much simpler solution would be if, upon the mod reaching the end of the movement script, before restarting, it would unload the file and then reload it. This would mean simply saving the scene in notepad++ would lead to the new movements being loaded automatically.

If the user has set the movement camera to be the main one shown in the desktop window, this would be an incredibly efficient way of testing positions and transitions, as it would just reload the file and show the new movement keyframes.

**Comment by kinsi55** [comment]
You can already hot-reload the entire cam2 config, including movement scripts, as outlined in the wiki.
