### ISSUE TITLE
Camera2 cameras not picking up extra Counters+ canvases

### ISSUE THREAD

**Issue by dawnvt** [kinsi55/CS_BeatSaber_Camera2#53]
Camera will not pick up Counters+ canvas, issue cropped up in 0.6.4.

Not sure if it's a Counters+ 2.2.2+ issue, or if it's a Cam2 0.6.4 issue.

Config:
[Camera2.zip](https://github.com/kinsi55/CS_BeatSaber_Camera2/files/7729551/Camera2.zip)

**Comment by kinsi55** [comment]
I dont think I changed anything in that regard in the past two versions - I personally havent experienced it either. Do you possibly have a video?

**Comment by dawnvt** [comment]
The view *should* be in the top right; But, it's not there

[Showcase](https://streamable.com/zx9j75)

**Comment by kinsi55** [comment]
Oh I see the Problem now - Your view is positioned incorrectly. That even being possible is more or less a bug of the ingame position adjustment. That Cameras viewRect `x` is set to 1, which puts the bottom left corner of it all the way to the right of the screen, putting it off the screen. Set it to 0.4.

**Comment by dawnvt** [comment]
Thank so much!
