### ISSUE TITLE
Game freeze during exit with pop up notification

### ISSUE THREAD

**Issue by ZombieBrine13092** [kinsi55/CS_BeatSaber_Camera2#54]
Please describe in detail what issue you encounter and potentially why you think it is a bug and not expected behaviour.

When the game exits (pressing the in-game menu's quit button), Camera2 will halt the game's shutdown until its notification box is closed on the desktop.
The notification box that I'm referencing is the one that pops up when you right click the game window and it tells you to use the in-game setup.

[Camera2.zip](https://github.com/kinsi55/CS_BeatSaber_Camera2/files/7748549/Camera2.zip)

**Comment by kinsi55** [comment]
I've been aware of this for quite some time now but the truth is that it is such a minor edgecase that I chose to ignore it

**Comment by kinsi55** [comment]
I removed the popup 👍
