### ISSUE TITLE
switch cameras with button

### ISSUE THREAD

**Issue by gianludoge** [kinsi55/CS_BeatSaber_Camera2#55]
i'm working to do a multiple camera setup for videos, the current way i'm doing it is by setting 4 cameras, and putting them in 1/4 of the screen, then capturing the image in obs and then switching to scenes wich are displaying the image in fullscreen, the only problem is that the resolution of the image is bad.
my idea is that u can switch cameras by binding a key on the controller or maybe by a fixed or random ammount of time

**Comment by kinsi55** [comment]
You can already do these - It just works slightly differently:

If you want to switch to a different camera manually, the indended way to do that is to use Custom Scenes. With that you can bind a specific set of Cameras to a keyboard key: https://github.com/kinsi55/CS_BeatSaber_Camera2/wiki/Scenes#custom-scenes

If you want to switch to a different camera automatically / randomly, what you are meant to do is not actually switch to a different camera, but to use a "Movement Script". You can specifc specific positions / rotations and FOV for a Camera to have at a specific point in time if it happens to use that Movement Script - To accomplish the randomness factor, you can use multiple scripts with different set of positions and rotations: https://github.com/kinsi55/CS_BeatSaber_Camera2/wiki/Movement-Scripts

**Comment by gianludoge** [comment]
ty so much ^•^, with the help of autohotkey pressing the keys in a sequence i actually managed to do that, ty really so much i was trying for ages QwQ https://youtu.be/EF25z3nUtEQ

**Comment by kinsi55** [comment]
You're welcome, however I would definitely advise you to look into movement scripts, it offers much more flexibility and is (once you get it) much easier 👍
