### ISSUE TITLE
Can not click play

### ISSUE THREAD

**Issue by XlonewolfrrpX** [kinsi55/CS_BeatSaber_Camera2#59]
When I load up the game and I select a song it wont play Ive made sure its this mod please help me figure this out. Thank you.

**Comment by kinsi55** [comment]
Please start the game, click on play, close it, and attach the _latest.log from the logs folder

**Comment by XlonewolfrrpX** [comment]
[_latest.log](https://github.com/kinsi55/CS_BeatSaber_Camera2/files/7903034/_latest.log)

**Comment by kinsi55** [comment]
Your Camera2 is outdated - Update it.

**Comment by XlonewolfrrpX** [comment]
ok thank you

**Comment by kinsi55** [comment]
In fact, a lot of your mods are outdated. I'd recommend going over / updating all of them.

**Comment by XlonewolfrrpX** [comment]
ok ill do that again thank you

**Comment by XlonewolfrrpX** [comment]
ok what is the best mod manger for beatsaber

**Comment by kinsi55** [comment]
See https://bsmg.wiki/ / the BSMG Discord if you need help unrelated to Cam2
