### ISSUE TITLE
Window mode issue with Counters+

### ISSUE THREAD

**Issue by Meivyn** [kinsi55/CS_BeatSaber_Camera2#6]
Looks like Camera2 is conflicting in some way with Counters+ since this isn't happening with CameraPlus. But the issue seems hard to track, as it wasn't happening with ONLY core mods, Counters+ and Camera2 installed. But it happened as soon as I installed back Counters+ while I was also using Camera2 and other mods.

Basically, every time you launch the game, the game is launched in windowed mode, no matter what's your game options. Fullscreen is always toggled back to off every time you relaunch the game.

Since this seems to be a relatively complex issue, I attached logs before/after this happened.

Before: the game was fresh the previous launch, now I install mods and launch the game. It wasn't happening.
After: relaunch the game, now it is in windowed mode.

[_latest_before.log](https://github.com/kinsi55/CS_BeatSaber_Camera2/files/6046272/_latest_before.log)
[_latest_after.log](https://github.com/kinsi55/CS_BeatSaber_Camera2/files/6046273/_latest_after.log)

**Edit:** Nevermind, it seems to happens also with CameraPlus.

**Comment by kinsi55** [comment]
> Edit: Nevermind, it seems to happens also with CameraPlus.

I was gonna say, I'm not doing anything in terms of changing the Fullscreen state, but I do know that it is a common issue that the game doesnt correctly determine if you have Fullscreen on or off. I dont think there is really a fix for this, I believe there is some mod in BSMG which you can use to force fullscreen on / off depending on what you configure it.

**Comment by Meivyn** [comment]
As I said, it started happening ONLY after installing Counters+ on top of Camera2 or CamerPlus, so it isn't an issue with the game. But it doesn't happen with only these mods installed. So basically you have at least three mods that conflict when they are installed all together.

**Comment by kinsi55** [comment]
https://discord.com/channels/441805394323439646/443146108420620318/805827892998176879

Here's the fullscreen plugin I was mentioning. If you search the BSMG discord for the word "fullscreen" and scroll through the messages you find people here and there that have the same issue, you're not alone with the problem and it existed before Cam2 was around even.

**Comment by Meivyn** [comment]
Yeah nevermind, I uninstalled both CameraPlus/Camera2 and Counters+ and in fact it was still happening. I just don't get why it started as soon as I installed Counters+, and stopped after removing Camera2/CameraPlus and vice-versa.

**Comment by kinsi55** [comment]
Because its an issue that happens randomly and you just randomly happened to encounter it in that unfortunate moment :P

**Comment by Meivyn** [comment]
Actually, no bug is random, so there must be a reason for that.

**Comment by Meivyn** [comment]
Just a heads up, we found what was causing this: https://github.com/monkeymanboy/BeatSaberMarkupLanguage/pull/85

**Comment by kinsi55** [comment]
Tfw the only dependency you rely on causes bug. Good job!
