### ISSUE TITLE
New camera preset to add to the list!

### ISSUE THREAD

**Issue by Squares2020** [kinsi55/CS_BeatSaber_Camera2#64]
I went through all the presets and found one that I think might be very nice to have and thats a camera that focuses on the accuracy so people can clearly see the percentage the player has. I know with Counters+ you can move it but if someone wants to move it around then uhhh idk but if you had the preset id just move it so its aligned with the camera as its a handy camera to have especially for tournaments. :D

**Comment by kinsi55** [comment]
As you stated, Counters+ is a problem with this - but an even bigger problem is that the counter position even differs per environment so yeah, I thought about adding this before but decided against it sorry. Despite, manually creating such a camera is simple enough to warrant not needing a preset for it.
