### ISSUE TITLE
Lock other rotation axes for first-person cameras.

### ISSUE THREAD

**Issue by VisibleReality** [kinsi55/CS_BeatSaber_Camera2#67]
It would be great if there was a feature to lock the other rotation axes of a first person camera. There already is an option to force the camera to not rotate side-to-side, but it would be good to be able to lock the other rotation axes too.

This would be useful because I have a bad habit of looking down sometimes while I'm playing, and while this is fine from my perspective, from the perspective of people watching it, like half the screen is just the platform and the notes are cut off on the top of the screen.

**Comment by kinsi55** [comment]
Theres a Pitch option in the Settings which you can use to pitch up the camera more. I dont think I would want to add options to lock other axis
