### ISSUE TITLE
Aspect of canvas on desktop is locked to 4:3

### ISSUE THREAD

**Issue by AaronCompNetSys** [kinsi55/CS_BeatSaber_Camera2#68]
I have a 4k TV as primary monitor. ALT+enter toggle and both canvas are locked to 4:3 instead of using the whole display. Windows 11, 1.20 game

Resetting to default its the same, the mod starts up this way.

**Comment by AaronCompNetSys** [comment]
![image](https://user-images.githubusercontent.com/7646740/160517602-e140a2b7-e29c-46e4-94da-cb3ee2e2f45a.png)

**Comment by kinsi55** [comment]
The size of the desktop window is not comething that Camera2 influences - It simply uses what is available. See the game options
