### ISSUE TITLE
Unable to manually overflow the ViewPort values

### ISSUE THREAD

**Issue by pasketi** [kinsi55/CS_BeatSaber_Camera2#69]
https://github.com/kinsi55/CS_BeatSaber_Camera2/blob/c1dbcb5893414dd308b5af60e88f01f059d05eb5/Behaviours/CamerasViewport.cs#L20

I'd like to be able to set values outside of the 0-1 range for ViewRect values, is possible. This doesn't need to be possible in-game, but I'd like the configuration to be taken as is, if negative values or values >1 are assigned to the config json manually.

The reason I want this is I want to center the first person camera view in the viewport without having black bars on one side of the screen. Just offsetting the camera location by setting the target position x-value will distort the view too much when using a perspective camera, since the camera will be physically placed on the side. I still want the camera to be directly behind the players head, but the center of the viewRect to be offset in the Viewport.

Example of a valid config:
```json
...
  "orthographic": false,
  "viewRect": {
    "x": -0.2,
    "y": 0.0,
    "width": 1.2,
    "height": 1.0,
    "locked": true
  },
...
```

**Comment by kinsi55** [comment]
I dont fully understand your usecase, can you provide a sample screenshot?

**Comment by pasketi** [comment]
![image](https://user-images.githubusercontent.com/5417056/161829593-621783e6-62cb-444f-b39b-ab342276b48e.png)

My use case would be to offset the center of the camera view in my viewport without losing perspective. Practically this would give more space on the screen for an avatar or UI

**Comment by kinsi55** [comment]
I see. Well, fwiw the code you linked isnt whats preventing you from doing it, but its rather these

https://github.com/kinsi55/CS_BeatSaber_Camera2/blob/c1dbcb5893414dd308b5af60e88f01f059d05eb5/Configuration/CameraSettings.cs#L347-L348

If you know how to / can compile a custom version, remove the Math.Min there and that should be it. Until then, I'll consider it for a future update

**Comment by kinsi55** [comment]
Implemented, will be in the next update
