### ISSUE TITLE
3rd person camera the world bugs out

### ISSUE THREAD

**Issue by itsjustkatiee** [kinsi55/CS_BeatSaber_Camera2#70]
I'm not sure how to explain it but when in 3rd person camera the world around is non existent. Not sure if it's a conflict with the avatar mod or not...I hope i've done this right i've never done this before.

Any questions please ask!
![image](https://user-images.githubusercontent.com/103080081/161866981-ac3c9102-35d5-46f1-a9fa-5c748c1c3edd.png)

**Comment by kinsi55** [comment]
Can you zip your camera2 config folder and attach it

**Comment by itsjustkatiee** [comment]
[Camera2.zip](https://github.com/kinsi55/CS_BeatSaber_Camera2/files/8422515/Camera2.zip)
is this what you mean? (i'm so sorry i genuinely have no idea what i'm doing)

**Comment by kinsi55** [comment]
Not exactly, in your beat saber folder theres a folder called userdata - In there, theres a folder called camera2. A zip of that folder is what I need

**Comment by itsjustkatiee** [comment]
[Camera2.zip](https://github.com/kinsi55/CS_BeatSaber_Camera2/files/8422521/Camera2.zip)
ah no worries! here you go ^_^

**Comment by kinsi55** [comment]
The Camera you are using was created from the Back View preset which pre-configures some settings, one of those being a shorter / limited render distance. If you go to the visibility tab and click on unlimited at the bottom you're remove that

**Comment by itsjustkatiee** [comment]
omg wow i'm such an idiot haha so sorry about this but thank you anyways ^_^
