### ISSUE TITLE
First-person camera is a little too far in replays

### ISSUE THREAD

**Issue by Sandfire5618** [kinsi55/CS_BeatSaber_Camera2#75]
Not sure if this has been taken into account yet but when in replay mode, the first-person camera seems to be backed up to where the spectator position is. The camera still follows the same motion as the HMD in the replay but it just seems too far away.

I found an option in settings that I thought was about taking the camera off the spectator position in replays but I turned it off and the camera is still in the same position. I just wish the camera was in the same HMD position in replay mode as it is when I'm actually playing a map. Just so when I record my replays for youtube, the camera is in the same POV as usual.

Not sure if this is a bug or not so I'm just labeling it as a suggestion.

**Comment by kinsi55** [comment]
I've been asking ScoreSaber for a way to get the real head position for over a year now to no avail - So The only thing I have access to is the pre-smoothed, offset head position. This offset is applied by ScoreSaber and you can change it in the ScoreSaber config

**Comment by Sandfire5618** [comment]
And how would I do that exactly?

**Comment by kinsi55** [comment]
In the UserData folder in your Beat Saber install, theres a ScoreSaber folder with a ScoreSaber.json file. Open that in Notepad and set `replayCameraZOffset` to 0

**Comment by Sandfire5618** [comment]
Got it! thanks!
