### ISSUE TITLE
Enforce V-Sync

### ISSUE THREAD

**Issue by BionicBison05** [kinsi55/CS_BeatSaber_Camera2#76]
Is it possible to enforce v-sync for the smooth camera window? No matter what I do, there's tearing in the main window, probably because of my 80hz headset. Or would this be outside the scope of Camera2's capabilities?

**Comment by kinsi55** [comment]
Syncing / the Framerate is enforced by the VR implementation, be it Oculus or Steam VR. Its not possible to decouple the Desktop framerate from the VR one in Unity unfortunately
