### ISSUE TITLE
Screen goes black while exiting level editor

### ISSUE THREAD

**Issue by Glytch10** [kinsi55/CS_BeatSaber_Camera2#77]
I'm one of the (few, probably) users of the new Beat Saber level editor built-in to the game, and I discovered an issue with this mod while making levels. 

While creating the level and entering the level editor, it works fine, but when you exit the editing mode to go back to the list of custom levels, the screen goes black and doesn't respond to inputs. The headset still displays "The level editor doesn't work in VR, please see your desktop" or whatever other message it says.

I tested both with the mod installed and with the mod not installed, as well as testing out if any of my other mods are causing the conflict--it worked with Camera2 removed and didn't with it installed.

Perhaps I could be missing a config setting that can prevent this from happening, but as of yet I am unaware of it.

Edit: This also was discovered without FPFC enabled, I haven't tried reproducing it with FPFC

Thank you for making and maintaining such a wonderful addition to Beat Saber's mod collection!

**Comment by kinsi55** [comment]
Are you entering the editor with the launch argument or with the button in the menu?

**Comment by Glytch10** [comment]
From the menu. I didn’t know there was a launch argument for the editor

**Comment by kinsi55** [comment]
I'm unable to replicate this. Can you replicate it, and afterwards take the _latest.log file in the logs folder, probably zip it because I expect its gonna be sizable, and attach that?

**Comment by kinsi55** [comment]
Oh, entering a song, that was the missing puzzle piece. I could replicate it now, I'll look into it.

**Comment by kinsi55** [comment]
Will be fixed in the next release
