### ISSUE TITLE
Text change needed for the "Move Display" button, as right click poup was removed

### ISSUE THREAD

**Issue by DrummerWasTaken** [kinsi55/CS_BeatSaber_Camera2#79]
As of v0.6.94, the right click popup was removed, as according to the changelog, "It should have done it's work by now". However clicking the "Move Display" button from the in-game menu still says to right click on the desktop for details for moving the window, which doesn't exist anymore. "Changing the size/position of a camera screen is done on the desktop window **(right click on the desktop for more details)**. If you really want to do it from in game however, clicking this button unlocks a secret settings tab ("Display") where you can do that in a crude way."

**Comment by kinsi55** [comment]
Yup forgot that, thanks
