### ISSUE TITLE
camera2 makes scoresaber's frame renderer's camera look at the ground or something

### ISSUE THREAD

**Issue by spenduo** [kinsi55/CS_BeatSaber_Camera2#8]
turn on scoresaber's frame renderer in the scoresaber config, and set where you want your frames to be in. then play a replay (the replay will seem slow), and look at the frames. the frames will have nothing on them because it's looking at the ground or something? without camera2 scoresaber's camera is at the player's headset and the frames show what's happening in game

what it should show: ![00300](https://user-images.githubusercontent.com/80223997/110255565-3f85b700-7f49-11eb-87f9-c5a816ae5e35.png)

what it shows with camera2: ![00300](https://user-images.githubusercontent.com/80223997/110255686-cf2b6580-7f49-11eb-8247-c6d05005d127.png)

[Camera2.zip](https://github.com/kinsi55/CS_BeatSaber_Camera2/files/6097983/Camera2.zip)

**Comment by kinsi55** [comment]
Huh, I had no idea this feature even existed. Is there any reason for you using it over simply recording the Game?

Camera2 entirely disables the Camera which Scoresaber creates to remove unnecessary load (As Camera2 "overwrites" it since Cam2 cameras are "above" it in the window), that would probably the reason why this isnt working for you.

**Comment by spenduo** [comment]
> Huh, I had no idea this feature even existed. Is there any reason for you using it over simply recording the Game?
> 
> Camera2 entirely disables the Camera which Scoresaber creates to remove unnecessary load (As Camera2 "overwrites" it since Cam2 cameras are "above" it in the window), that would probably the reason why this isnt working for you.

I use it because I'm too lazy to change my monitor's resolution to 1080p everytime I record a replay

**Comment by kinsi55** [comment]
What is your monitors resolution otherwise? If its just about the game not being fullscreen, you can toggle fullscreen with Alt+Enter.

**Comment by spenduo** [comment]
> What is your monitors resolution otherwise? If its just about the game not being fullscreen, you can toggle fullscreen with Alt+Enter.

i use 960p540

**Comment by kinsi55** [comment]
Well, I'll see what I can do about this in the next update.

**Comment by spenduo** [comment]
ok thanks

**Comment by kinsi55** [comment]
No need to close the issue while it still is.. an issue :P

**Comment by spenduo** [comment]
> No need to close the issue while it still is.. an issue :P

oh
