### ISSUE TITLE
Support of YAML files

### ISSUE THREAD

**Issue by blackorbit1** [kinsi55/CS_BeatSaber_Camera2#86]
Json is great for its wide support and its simplicity but is not the most scalable and human friendly configuration language.
I've really started to suffer from the json simplicity when I tried to make a video with lots of camera movements.

I think being able to use yaml with it's much simpler syntax and the ability to write comments would help in creating camera scripts.
Here's a quick comparison :
![image](https://user-images.githubusercontent.com/38140797/190020331-93d832eb-81ae-43a6-9d1a-a45709e1fe6a.png)

I know it is possible to write comments in fake attributes but it doesn't stand out like real comments.

It shouldn't require having 2 parallels methods of config reading for retro compatibility because json is a subset of yaml (you can mix json and yaml syntax together).

I've also seen there are CS library to easly parse YAML. On the reading side, with a little bit of chance the only required modification could be to change the library used to parse the config but I don't know what would be the implication on the writing side.
Maybe the mod could read yaml and json but only write yaml (so any json file could be changed to a yaml file if needed), or maybe it could only consider files with the `json` or `yaml` extension and parse them as yaml.

Also I don't know what would happen with the comments if the file is modified.

**Comment by kinsi55** [comment]
Not happening, most people already barely know how to properly edit JSON, I'm not gonna throw a format at people that requires correct indentation (Especially with not a singular other mod using this format) - And adding it optionally would imo be feature creep.

That being said, are you aware [B2C2](https://github.com/KandyWrong/blender2camera2#blender2camera2) exists?

**Comment by blackorbit1** [comment]
Oh no I never heard about it :o thanks for the link ^^
Maybe it could be interesting to add a link somewhere here https://github.com/kinsi55/CS_BeatSaber_Camera2/wiki/Movement-Scripts like

> # Movement Scripts (Camera2/MovementScripts/*.json)
> The "known" format for movement scripts was changed from Camera Plus, it is no longer a list of movements, but of keyframes. If you try to load a Camera Plus movement script with Camera2 it will be converted to the new format automatically.
> For advanced movement scripting, you can check <a href="https://kandywrong.com/b2c2/introduction.html#what-this-guide-covers">Blender2Camera2</a>. It is a separate project made by KandyWrong to help creating movement scripts through Blender.

tbh I was thinking about trying to do it as a first contribution but yeah the benefits would be really small if the implementation is not super simple and don't have any side effect on json users.

**Comment by kinsi55** [comment]
It is mentioned in the FAQ, but yeah maybe I should add it to the Movement Scripts page too
