### ISSUE TITLE
An option of smoothly transition in the movement script like CameraPlus.

### ISSUE THREAD

**Issue by nanafus** [kinsi55/CS_BeatSaber_Camera2#9]
I know that there are existing options, Linear or Eased, but the option of Eased is the movement like an arch, if my perception is correct. Would you like to add the option of smoothly changing the movement speed like the "EaseTransition" in CameraPlus? 
I'd love to use elegant scripts!

**Comment by kinsi55** [comment]
I had noticed before that Eased does not seem to do exactly what I would like it to, its supposed to slowly ramp up in speed, and then slowly decline again at the end, I just havent gotten around yet to looking into this change. As far as I understand, that is what you're looking for?

**Comment by nanafus** [comment]
Exactly you understand what I thought. The existing Eased option is useful but I would also like to change the speed gradually up and down in the transition, if possible.

**Comment by kinsi55** [comment]
I'll probably ditch the current Implementation of Eased in favor of an actual eased one and maybe add a couple more possible easings in. I dont think the current Eased implementation really has much use, unless you know of one?

**Comment by nanafus** [comment]
OK. I’m looking forward to your update.

**Comment by kinsi55** [comment]
This change is now implemented in the 0.3.8 Beta release: https://github.com/kinsi55/CS_BeatSaber_Camera2/releases/tag/v0.3.8
