### ISSUE TITLE
viewRect's x offset is forced to a negative number relative to the width's value

### ISSUE THREAD

**Issue by TheBlackParrot** [kinsi55/CS_BeatSaber_Camera2#92]
Trying to offset my first person view to a different position and cam2 is changing that value relative to what i set for the width value.
If I want
```json
  "viewRect": {
    "x": 0.3,
    "y": 0.0,
    "width": 1.5,
    "height": 1.0,
    "locked": false
  },
```
cam2 forces it to
```json
  "viewRect": {
    "x": -0.5,
    "y": 0.0,
    "width": 1.5,
    "height": 1.0,
    "locked": false
  },
```
upon reload / game restart.

**Comment by kinsi55** [comment]
This is actually intended to prevent people from accidently moving the camera completely offscreen and wondering where it went

**Comment by TheBlackParrot** [comment]
Completely took those lines out and built it myself tonight, stuff is positioning how I expect it to now.
