### ISSUE TITLE
Camera Displays Are Bound To Bottom-Left Area Depending On Their Sizes

### ISSUE THREAD

**Issue by christantoan** [kinsi55/CS_BeatSaber_Camera2#93]
Hello,

After updating to Camera2 v0.6.100, my camera display is bound to bottom-left area of the screen and I can't move it to top/right/top-right area. The bounding area depends on the camera display size with larger display equals larger bounding area. See recording below:

https://user-images.githubusercontent.com/7300310/202853303-c96689ac-13ec-4bab-b471-ec6cb533f408.mp4

Rolling back to v0.6.99 fixes this problem.
This is my Camera2 setting: [Camera2.zip](https://github.com/kinsi55/CS_BeatSaber_Camera2/files/10047098/Camera2.zip)

Hope this can be fixed.
Thank you.

**Comment by kinsi55** [comment]
Shortly after releasing that version I noticed an error in my logic and released a new build with the same version - could you try redownloading and seeing if its fixed?

**Comment by christantoan** [comment]
Thank you!
It's fixed now.

In other notes, do you know how to be notified when a Github Release file is updated? I'm using GitHub's Watch Releases feature but it won't notify me in cases like this. I've had this happened a couple of times already.

Thank you in advance!

**Comment by kinsi55** [comment]
I dont think theres a way to do that - Doing what I did there isnt really a good practice (for obvious reasons)

**Comment by christantoan** [comment]
I see.
Thank you anyway for developing and maintaining this plugin!! 😀
