### ISSUE TITLE
Cameras remain attached to platform after pause-restart, even if player track moves.

### ISSUE THREAD

**Issue by makyo** [kinsi55/CS_BeatSaber_Camera2#95]
If you play through a modmap partway, pause, and restart from the pause menu, the cameras seem to remain attached to the platform rather than the player. This applies to first person and positionable cameras (haven't tried with attached yet).

Example:

* [Playing from beginning with no pause](https://youtu.be/089iIqgIAvc)
* [After restarting from pause](https://youtu.be/H1_6_iGCh9A)

([Here's the video where I discovered it](https://www.youtube.com/watch?v=HmqotjdCUww))

[Camera2 configs](https://gist.github.com/makyo/517216536ef8ec00f2ba7399837f436b) - cameras are mod1pov and mod3pov

**Comment by makyo** [comment]
Additional note: I've noticed similar behavior in Nalaluna Rewinder. I don't know if that makes it more or less likely to be just me.

**Comment by kinsi55** [comment]
Hey, thanks for the report I'll try to look into it later today. What game version are you on?

**Comment by makyo** [comment]
1.26, here!

**Comment by FEFELAND** [comment]
Ah, I see this has already been posted. Yeah I too noticed player following breaks after a restart. Be it third person cams or first person cams. I've noticed before but only recently discovered it was because of restart.  (The seemingly fast load times in this video is cuz it's edited)

Game: 1.29.1
Cam2: 0.6.100.0

https://github.com/kinsi55/CS_BeatSaber_Camera2/assets/57236015/ed1a9f71-ae8d-4076-96c1-8b252110755d

**Comment by roboltz** [comment]
I'm not sure if this is the same problem for me but it does that same thing with the camera even when I don't restart, the player following just doesn't work.
![2023-09-09 14-45-39](https://github.com/kinsi55/CS_BeatSaber_Camera2/assets/77972303/1ccd6437-874e-4fcc-862d-4b0ffe712b18)

**Comment by kinsi55** [comment]
@roboltz thats a different issue (Fixed in new release), this issue however still exists.

**Comment by kinsi55** [comment]
Fixed in latest release

**Comment by ND-fond** [comment]
Sorry to disturb. I have Beat Saber v1.40.5 and the latest version is Camera2. And I have this problem. This may be due to the reduced time between restarts.

**Comment by kinsi55** [comment]
@ND-fond Time between restarts shouldnt have anything to do with it, nothing in cam2 is based off delays. Mind posting your camera 2 config folder?

**Comment by ND-fond** [comment]
@kinsi55 

[Camera2.zip](https://github.com/user-attachments/files/21146518/Camera2.zip)
