### ISSUE TITLE
Camera2 fails to load on 1.27

### ISSUE THREAD

**Issue by TheBlackParrot** [kinsi55/CS_BeatSaber_Camera2#96]
Tried BS 1.27 out since it's been public for a bit, can't get Camera2 to load due to something with Harmony (looks like a few other plugins have issues with it too)
[2023.01.03.06.37.38.log](https://github.com/kinsi55/CS_BeatSaber_Camera2/files/10336237/2023.01.03.06.37.38.log)

**Comment by kinsi55** [comment]
Camera2 itself works fine, its your outdated version of modhcart that has the side effect of breaking cam2
