### ISSUE TITLE
Camera movement is delayed in fpfc w/ cam2

### ISSUE THREAD

**Issue by losowyLP** [kinsi55/CS_BeatSaber_Camera2#97]
After launching Beat Saber with the fpfc launch argument and moving the mouse around i expect for it to behave normally and give me almost instant feedback. I've tried this w/o cam2 as well and it worked just fine. But after I installed cam2 again, any visual feedback has become extremely delayed.

Video of the issue ocurring:
https://user-images.githubusercontent.com/77402345/214895594-33b965fc-ec5d-4519-9244-ac078ffa0c7b.mp4

My /UserData/Camera2 folder:
[Camera2.zip](https://github.com/kinsi55/CS_BeatSaber_Camera2/files/10511515/Camera2.zip)

**Comment by kinsi55** [comment]
I have never seen this issue before and I cannot imagine why that would happen.

Can you start the game up with fpfc again and then send me the `_latest.log` from the logs directory?

**Comment by losowyLP** [comment]
Here you go:
[_latest.log](https://github.com/kinsi55/CS_BeatSaber_Camera2/files/10513936/_latest.log)

**Comment by kinsi55** [comment]
That did not shed any more light into the dark. I'll ask others and see if anyone of them might have any idea whats going on

**Comment by kinsi55** [comment]
A couple of things:

- Is your VR headset connect? Depending on if it is / isnt, does changing to the other state make a difference?
- When you move the Controller, is that also reflected delayed or is that instant?
- Do you have an AMD GPU?

**Comment by losowyLP** [comment]
A couple of things:

Is your VR headset connect? Depending on if it is / isnt, does changing to the other state make a difference?
When you move the Controller, is that also reflected delayed or is that instant?
Instead of using Cam2, when you use the basegame Smooth Camera does that have the same issue?
Do you have an AMD GPU?

Some of these things i can't try out because I'll be at school, so I'll try again once I'm home
No my VR headset isn't connected. This is usually the case when I use fpfc.
In VR I don't have any issues with this, only in fpfc.
When using Smooth Cam I also don't have this issue at all.
Yes, I'm using a RX 6600 from Sapphire. 

When I analyze the issue closer it seems that only the video output it delayed, because all the sounds come in when they actually are supposed to.

**Comment by losowyLP** [comment]
Some of these things i can't try out because I'll be at school, so I'll try again once I'm home
No my VR headset isn't connected. This is usually the case when I use fpfc.
In VR I don't have any issues with this, only in fpfc.
When using Smooth Cam I also don't have this issue at all.
Yes, I'm using a RX 6600 from Sapphire. 

When I analyze the issue closer it seems that only the video output it delayed, because all the sounds come in when they actually are supposed to.

**Comment by losowyLP** [comment]
Also, this might be an issue that came along with some of the recent updates. This used to not happen at all, even with the AMD GPU and Cam2 enabled

**Comment by losowyLP** [comment]
Having the headset connected while using fpfc does in fact fix the issue

**Comment by kinsi55** [comment]
Then I think I know whats causing it, but I dont know why that would happen. Must be related to vsync (Which is forced by cam2 when no headset is connected as otherwise the game would run at uncapped FPS) - But again, I have no idea why that would cause so much latency for you. Maybe try and play around with some driver options related to that?

**Comment by losowyLP** [comment]
Think I got it. If I set the "Wait for Vertical Refresh" setting from "Off, unless application specifies" to "On, unless application specifies" from within the AMD Software, then the issue seems to be completely gone. If possible maybe you can try to tell the driver that the application uses V-Sync, and that'd fix the issue for anyone else having the issue?

**Comment by kinsi55** [comment]
Like I said, I've never seen this issue before ever by anyone, and the fact that you changing it to on fixes it makes it even more baffling.

I dont know how I'd report the state to the driver to be honest, I think this is something that should be handled by Unity (I'm using builtin engine features)

**Comment by kinsi55** [comment]
I got a couple of reports that this can even happen without camera2 in certain circumstances - I dont think there is anything I can really do to resolve this on my end, just an unfortunate setup specific issue so I'll close this here
